run:
  skip-files:
    - "tests/integration/.*\\.go$"
  skip-dirs-use-default: true
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
